name: "App & Docs"
cmd: "gulp"
cwd: "{PROJECT_PATH}"
targets:
  Version Bump:
    cmd: "gulp version_bump"
    cwd: "{PROJECT_PATH}"
  App:
    cmd: "gulp app"
    cwd: "{PROJECT_PATH}"
  Docs:
    cmd: "gulp docs"
    cwd: "{PROJECT_PATH}"
