version: 2
jobs:
  rspec:
    docker:
      - image: ellislab/eecms-test:headless-chrome
        auth:
          username: $DOCKER_USERNAME
          password: $DOCKER_PASSWORD
    steps:
      - checkout
      - run: chmod +x ./eetools
      - run:
          name: Run rSpec Tests
          command: ./eetools test

workflows:
  version: 2
  build_and_test:
    jobs:
      - rspec
