version: 2
jobs:
  test_php_54:
    docker:
      - image: docker:stable-git
    steps:
      - setup_remote_docker
      - checkout
      - run: |
          git config --global user.email "you@example.com"
          git config --global user.name "Your Name"
      - run: |
          apk update
          apk upgrade
          apk add bash
      - run: chmod +x ./eetools
      - run: bash ./eetools circleci -p 5.4.46
      - store_artifacts:
          path: /tmp/artifacts
  test_php_55:
    docker:
      - image: docker:stable-git
    steps:
      - setup_remote_docker
      - checkout
      - run: |
          git config --global user.email "you@example.com"
          git config --global user.name "Your Name"
      - run: |
          apk update
          apk upgrade
          apk add bash
      - run: chmod +x ./eetools
      - run: bash ./eetools circleci -p 5.5.38
      - store_artifacts:
          path: /tmp/artifacts
  test_php_56:
    docker:
      - image: docker:stable-git
    steps:
      - setup_remote_docker
      - checkout
      - run: |
          git config --global user.email "you@example.com"
          git config --global user.name "Your Name"
      - run: |
          apk update
          apk upgrade
          apk add bash
      - run: chmod +x ./eetools
      - run: bash ./eetools circleci -p 5.6.32
      - store_artifacts:
          path: /tmp/artifacts
  test_php_70:
    docker:
      - image: docker:stable-git
    steps:
      - setup_remote_docker
      - checkout
      - run: |
          git config --global user.email "you@example.com"
          git config --global user.name "Your Name"
      - run: |
          apk update
          apk upgrade
          apk add bash
      - run: chmod +x ./eetools
      - run: bash ./eetools circleci -p 7.0.25
      - store_artifacts:
          path: /tmp/artifacts
  test_php_71:
    docker:
      - image: docker:stable-git
    steps:
      - setup_remote_docker
      - checkout
      - run: |
          git config --global user.email "you@example.com"
          git config --global user.name "Your Name"
      - run: |
          apk update
          apk upgrade
          apk add bash
      - run: chmod +x ./eetools
      - run: bash ./eetools circleci -p 7.1.11
      - store_artifacts:
          path: /tmp/artifacts

workflows:
  version: 2
  build_and_test:
    jobs:
      - test_php_54
      - test_php_55
      - test_php_56
      - test_php_70
      - test_php_71
