version: 2
jobs:
  rspec:
    docker:
      - image: docker:stable-git
    steps:
      - setup_remote_docker
      - checkout
      - run:
          name: Grab our Docker Container
          command: |
            docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
            docker pull ellislab/eecms-test:headless-chrome
      - run: chmod +x ./project/eetools
      - run:
          name: Start Tests
          command: ./eetools test

workflows:
  version: 2
  build_and_test:
    jobs:
      - rspec
