version: 2
jobs:
  rspec:
    docker:
      - image: docker:stable-git
    steps:
      - setup_remote_docker
      - checkout
      - run: |
          git config --global user.email "you@example.com"
          git config --global user.name "Your Name"
      - run:
          name: Log in for Docker
          command: |
            docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
      - run: |
          apk update
          apk upgrade
          apk add bash
      - run: chmod +x ./eetools
      - run:
          name: Start Tests
          command: ./eetools test

workflows:
  version: 2
  build_and_test:
    jobs:
      - rspec
